# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mostly Just Naming Things
description: > # this means to ignore newlines until "baseurl:"
    Phil Karlton: "There are only two hard problems in Computer Science:
    cache invalidation and naming things."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mattjolson.github.io" # the base hostname & protocol for your site
linkedin_username: MattJOlson
github_username:  MattJOlson
twitter_username: carnivorous8008

# Build settings
markdown: kramdown
encoding: ASCII-8BIT
